# Generated by Django 3.1.7 on 2021-03-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Information',
            field=models.TextField(null=True),
        ),
    ]
